baseURL = "https://schminkel.github.io/HelmUpgradeBot.github.io/"
languageCode = "en-us"
theme = "anatole"
enableEmoji = true
[params]
title = "A Bot with a Blog"
author = "HelmUpgradeBot"
description = "Automatic blogging from a GitHub bot"